### ISSUE TITLE
Cannot Access API from pipeline

### ISSUE THREAD

**Issue by SidGrundfos** [neumanndaniel/terraform#1]
Hi Daniel,
This is not an issue, but I am trying to add security to my infrastructure and whitelisting Ips was the first step. In my case when I add the ips after cluster deployment the other steps after the same starts failing. Like creating namespaces, ingress controller etc. the issue is cannot reach the API.
![image](https://user-images.githubusercontent.com/53938860/72245719-75533800-35f1-11ea-8fde-02da0f20ca96.png)

I am using azure hosted agents (ubuntu 16.04)
My org is in WE zone
I have included ips from WE, NE and FRANCE (fallback for WE)

Can you please help, I am stuck

**Comment by neumanndaniel** [comment]
Did you whitelist all IP ranges of West Europe, North Europe and France?

**Comment by aodj** [comment]
Apologies for replying to a closed issue, but I'm attempting to do the same thing (whitelist the IP ranges) and followed along with your [blog post](https://www.danielstechblog.io/secure-kubernetes-api-server-access-in-azure-kubernetes-service/) on the topic.

When attempting to do the same as you did, I'm getting notified that there' a 200 CIDR range limit for the AKS service: 

> The number of APIServer Authorized IP Ranges is greater than the allowed value 200.

This is supported by the [documentation](https://docs.microsoft.com/en-us/azure/aks/api-server-authorized-ip-ranges#create-an-aks-cluster-with-api-server-authorized-ip-ranges-enabled) as well. Was the number of CIDR ranges less when this blog post was written? I'm seeing somewhere north of 400 ranges when parsing the JSON file.

**Comment by neumanndaniel** [comment]
@aodj Back then I had 344 CIDR ranges, but this was over a year ago.

The limit has changed since last year: https://github.com/MicrosoftDocs/azure-docs/commit/84de95af899cfb061181fdafba4fcf70e8f5ec50#diff-b27639c6f03ca81da801e1302f2fcfc45b53d9cd5363f54848eeddb4502afbdb
