### ISSUE TITLE
ClusterUpgrade script - when is it required

### ISSUE THREAD

**Issue by asubmani** [neumanndaniel/terraform#3]
Hi Daniel,
I saw your cluster upgrade shell script. Is this still required? Could share some details on why we need this? I could not find it in the AKS list of issues using `mentions:neumanndaniel`

The script I am referring to is cluster-upgrade-fix.sh

**Comment by neumanndaniel** [comment]
@asubmani Still required until this issue is resolved.

-> https://github.com/terraform-providers/terraform-provider-azurerm/issues/5541

**Comment by neumanndaniel** [comment]
TF Azure provider version 2.14.0 fixes this and hence the script won't be required anymore.

-> https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/CHANGELOG.md#2140-unreleased

I close the issue now.
